// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Merp(arg1) {
  return window['go']['main']['App']['Merp'](arg1);
}

export function Ping(arg1) {
  return window['go']['main']['App']['Ping'](arg1);
}

export function Update() {
  return window['go']['main']['App']['Update']();
}
